
name: Build Python Wheels

on:
  push:
    branches: [master]

jobs:

  build_setup:
    name: Prepare environment for wheel builds
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare wheel build
        run: make -C python/ setup

  build_wheels:
    name: Build binary wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [build_setup]
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        arch: [auto32, auto64, aarch64, ppc64le, s390x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2
        working-directory: python/
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        working-directory: python/
        # env:
        #   CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: [build_setup]
    steps:
      - uses: actions/checkout@v2
      - name: Install cython
        run: python -m pip install cython==0.29.24
      - name: Build sdist
        run: python setup.py sdist
        working-directory: python/

  upload_pypi:
    name: Upload binary wheels to PyPI
    runs-on: ubuntu-20.04
    needs: [build_wheels, build_sdist]

    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.IMCTERMITE_GITHUB_WORKFLOW_PYPI_API_TOKEN }}
