
name: Build Python Wheels
on:
  push:
    branches:
      - master
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        arch: [auto32, auto64, aarch64, ppc64le, s390x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

  upload_wheels:
    name: Upload binary wheels to PyPI
    needs: [build_wheels]

    steps:
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.IMCTERMITE_GITHUB_WORKFLOW_PYPI_API_TOKEN }}
